### ISSUE TITLE
Doesn't install on python 3

### ISSUE THREAD

**Issue by th0th** [xaralis/django-static-sitemaps#31]
Hello,

I am trying to install with pip (7.1.1) on python (3.4.0).

When I try to install with command:

```
$ pip install django-static-sitemaps
````

I get this error:

```
Collecting django-static-sitemaps
  Using cached django-static-sitemaps-2.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-792ml56b/setuptools_dummy-0.1.0.4/setup.py", line 10
        print "can't find ez_setup"
                                  ^
    SyntaxError: invalid syntax

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-8z1g3cee/django-static-sitemaps/setup.py", line 38, in <module>
        'setuptools_dummy',
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/site/lib/python3.4/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/site/lib/python3.4/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/site/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/site/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/site/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/site/lib/python3.4/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/site/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/site/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/site/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/site/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/site/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/site/lib/python3.4/site-packages/setuptools/compat.py", line 65, in reraise
        raise value.with_traceback(tb)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/site/lib/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
        code = compile(script, filename, 'exec')
      File "/tmp/easy_install-792ml56b/setuptools_dummy-0.1.0.4/setup.py", line 10
        print "can't find ez_setup"
                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8z1g3cee/django-static-sitemaps
```

**Comment by artscoop** [comment]
I've just had the same error. The package info states it's only compatible with Python 2.7 for the moment (and it works with Python 2.7)

**Comment by xaralis** [comment]
@th0th Sorry, I have no spare time at the moment to port this package to Python 3, but will appreciate any PR if you're will to do it instead.

**Comment by lightstrike** [comment]
@xaralis Is @onpublico's [fork](https://github.com/onpublico/django-static-sitemaps) acceptable to merge? If not, what work needs to be done to get it to an acceptable state?

**Comment by xaralis** [comment]
@lightstrike It looks OK to me. The only issue I see is that `urlpatterns` are now not compatible with old Django versions which is probably acceptable. I'll merge it.

**Comment by xaralis** [comment]
https://github.com/xaralis/django-static-sitemaps/releases/tag/4.0.0

https://pypi.python.org/pypi/django-static-sitemaps
