### ISSUE TITLE
Bytes/String issues with GZip using Python 3 

### ISSUE THREAD

**Issue by techdragon** [xaralis/django-static-sitemaps#35]
Ran into an issue with string/bytes handling. Looks like it slipped through the cracks when adding the Python 3 support. `STATICSITEMAPS_USE_GZIP = False` serves as a workaround until a more permanent fix is written.
  
```
Generating sitemaps.
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/static_sitemaps/management/commands/refresh_sitemap.py", line 14, in handle_noargs
    generator.write()
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/static_sitemaps/generator.py", line 69, in write
    self.write_index()
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/static_sitemaps/generator.py", line 89, in write_index
    lastmod = self.write_page(site, page, filename)
  File "/home/techdragon/.pyenv/versions/test_project/lib/python3.4/site-packages/static_sitemaps/generator.py", line 175, in write_page
    with gzip.GzipFile(fileobj=buf, mode="w") as f:
  File "/home/techdragon/.pyenv/versions/3.4.3/lib/python3.4/gzip.py", line 220, in __init__
    self._write_gzip_header()
  File "/home/techdragon/.pyenv/versions/3.4.3/lib/python3.4/gzip.py", line 252, in _write_gzip_header
    self.fileobj.write(b'\037\213')             # magic header
TypeError: string argument expected, got 'bytes'
```

**Comment by xaralis** [comment]
@techdragon Would you mind looking into it? It will probably be just a minor correction somewhere...
